/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateVehicleInsuranceSol from "./PrivateVehicleInsurance.sol";
export type { privateVehicleInsuranceSol };
export type { PauserSet } from "./PauserSet";
