/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PauserSetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPauserCount"
      | "getPausers"
      | "isAuthorizedPauser"
      | "isPauser"
      | "pausers"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PauserAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPausers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pausers",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPausers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedPauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pausers", data: BytesLike): Result;
}

export namespace PauserAddedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PauserSet extends BaseContract {
  connect(runner?: ContractRunner | null): PauserSet;
  waitForDeployment(): Promise<this>;

  interface: PauserSetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  getPausers: TypedContractMethod<[], [string[]], "view">;

  isAuthorizedPauser: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  isPauser: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  pausers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPausers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedPauser"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pausers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;

  filters: {
    "PauserAdded(address)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
  };
}
