/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as privateVehicleInsuranceSol from "./PrivateVehicleInsurance.sol";
export { PauserSet__factory } from "./PauserSet__factory";
