/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPauserSet } from "./IPauserSet";
export type { PrivateVehicleInsurance } from "./PrivateVehicleInsurance";
