/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivateVehicleInsuranceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeReviewer"
      | "authorizedReviewers"
      | "calculateRiskScore"
      | "claimReviews"
      | "claims"
      | "createPolicy"
      | "getClaimDetails"
      | "getClaimStatus"
      | "getClaimsByHolder"
      | "getPoliciesByHolder"
      | "holderClaims"
      | "holderPolicies"
      | "insuranceCompany"
      | "isPauseAllowed"
      | "isPaused"
      | "nextClaimId"
      | "nextPolicyId"
      | "pause"
      | "pauserSetContract"
      | "policies"
      | "processPayment"
      | "protocolId"
      | "reviewClaim"
      | "revokeReviewer"
      | "submitClaim"
      | "unpause"
      | "updateInsuranceCompany"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimApproved"
      | "ClaimPaid"
      | "ClaimReviewed"
      | "ClaimSubmitted"
      | "ContractPaused"
      | "ContractUnpaused"
      | "PolicyCreated"
      | "ReviewerAuthorized"
      | "ReviewerRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeReviewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedReviewers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimsByHolder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByHolder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "holderClaims",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "holderPolicies",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "insuranceCompany",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPauseAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextClaimId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextPolicyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauserSetContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewClaim",
    values: [BigNumberish, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeReviewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitClaim",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateInsuranceCompany",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedReviewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimsByHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insuranceCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPauseAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextClaimId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPolicyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauserSetContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reviewClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateInsuranceCompany",
    data: BytesLike
  ): Result;
}

export namespace ClaimApprovedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    approvedAmount: BigNumberish
  ];
  export type OutputTuple = [claimId: bigint, approvedAmount: bigint];
  export interface OutputObject {
    claimId: bigint;
    approvedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimPaidEvent {
  export type InputTuple = [claimId: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [claimId: bigint, recipient: string];
  export interface OutputObject {
    claimId: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimReviewedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    reviewer: AddressLike,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    reviewer: string,
    newStatus: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    reviewer: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSubmittedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    policyId: BigNumberish,
    claimant: AddressLike
  ];
  export type OutputTuple = [
    claimId: bigint,
    policyId: bigint,
    claimant: string
  ];
  export interface OutputObject {
    claimId: bigint;
    policyId: bigint;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [policyId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [policyId: bigint, holder: string];
  export interface OutputObject {
    policyId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerAuthorizedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerRevokedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateVehicleInsurance extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateVehicleInsurance;
  waitForDeployment(): Promise<this>;

  interface: PrivateVehicleInsuranceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeReviewer: TypedContractMethod<
    [_reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedReviewers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  calculateRiskScore: TypedContractMethod<
    [_policyId: BigNumberish],
    [string],
    "nonpayable"
  >;

  claimReviews: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        claimId: bigint;
        reviewer: string;
        encryptedAssessedDamage: string;
        encryptedRecommendedPayout: string;
        reviewNotes: string;
        reviewedAt: bigint;
      }
    ],
    "view"
  >;

  claims: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        claimId: bigint;
        policyId: bigint;
        claimant: string;
        encryptedDamageAmount: string;
        encryptedRepairCost: string;
        encryptedApprovedAmount: string;
        status: bigint;
        severity: bigint;
        ipfsDocumentHash: string;
        submittedAt: bigint;
        processedAt: bigint;
        isConfidential: boolean;
      }
    ],
    "view"
  >;

  createPolicy: TypedContractMethod<
    [
      _age: BigNumberish,
      _drivingYears: BigNumberish,
      _vehicleValue: BigNumberish,
      _premium: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getClaimDetails: TypedContractMethod<
    [_claimId: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, bigint, bigint, boolean] & {
        policyId: bigint;
        claimant: string;
        status: bigint;
        severity: bigint;
        documentHash: string;
        submittedAt: bigint;
        processedAt: bigint;
        isConfidential: boolean;
      }
    ],
    "view"
  >;

  getClaimStatus: TypedContractMethod<
    [_claimId: BigNumberish],
    [bigint],
    "view"
  >;

  getClaimsByHolder: TypedContractMethod<
    [_holder: AddressLike],
    [bigint[]],
    "view"
  >;

  getPoliciesByHolder: TypedContractMethod<
    [_holder: AddressLike],
    [bigint[]],
    "view"
  >;

  holderClaims: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  holderPolicies: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  insuranceCompany: TypedContractMethod<[], [string], "view">;

  isPauseAllowed: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  nextClaimId: TypedContractMethod<[], [bigint], "view">;

  nextPolicyId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauserSetContract: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, boolean, bigint] & {
        holderAddress: string;
        encryptedAge: string;
        encryptedDrivingYears: string;
        encryptedVehicleValue: string;
        encryptedPremium: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  processPayment: TypedContractMethod<
    [_claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  reviewClaim: TypedContractMethod<
    [
      _claimId: BigNumberish,
      _assessedDamage: BigNumberish,
      _recommendedPayout: BigNumberish,
      _reviewNotes: string,
      _newStatus: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revokeReviewer: TypedContractMethod<
    [_reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  submitClaim: TypedContractMethod<
    [
      _policyId: BigNumberish,
      _damageAmount: BigNumberish,
      _repairCost: BigNumberish,
      _severity: BigNumberish,
      _documentHash: string,
      _isConfidential: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateInsuranceCompany: TypedContractMethod<
    [_newCompany: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeReviewer"
  ): TypedContractMethod<[_reviewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedReviewers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateRiskScore"
  ): TypedContractMethod<[_policyId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReviews"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        claimId: bigint;
        reviewer: string;
        encryptedAssessedDamage: string;
        encryptedRecommendedPayout: string;
        reviewNotes: string;
        reviewedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        claimId: bigint;
        policyId: bigint;
        claimant: string;
        encryptedDamageAmount: string;
        encryptedRepairCost: string;
        encryptedApprovedAmount: string;
        status: bigint;
        severity: bigint;
        ipfsDocumentHash: string;
        submittedAt: bigint;
        processedAt: bigint;
        isConfidential: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [
      _age: BigNumberish,
      _drivingYears: BigNumberish,
      _vehicleValue: BigNumberish,
      _premium: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimDetails"
  ): TypedContractMethod<
    [_claimId: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, bigint, bigint, boolean] & {
        policyId: bigint;
        claimant: string;
        status: bigint;
        severity: bigint;
        documentHash: string;
        submittedAt: bigint;
        processedAt: bigint;
        isConfidential: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimStatus"
  ): TypedContractMethod<[_claimId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaimsByHolder"
  ): TypedContractMethod<[_holder: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPoliciesByHolder"
  ): TypedContractMethod<[_holder: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "holderClaims"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "holderPolicies"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "insuranceCompany"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isPauseAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextClaimId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPolicyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauserSetContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, boolean, bigint] & {
        holderAddress: string;
        encryptedAge: string;
        encryptedDrivingYears: string;
        encryptedVehicleValue: string;
        encryptedPremium: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<[_claimId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reviewClaim"
  ): TypedContractMethod<
    [
      _claimId: BigNumberish,
      _assessedDamage: BigNumberish,
      _recommendedPayout: BigNumberish,
      _reviewNotes: string,
      _newStatus: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeReviewer"
  ): TypedContractMethod<[_reviewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitClaim"
  ): TypedContractMethod<
    [
      _policyId: BigNumberish,
      _damageAmount: BigNumberish,
      _repairCost: BigNumberish,
      _severity: BigNumberish,
      _documentHash: string,
      _isConfidential: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInsuranceCompany"
  ): TypedContractMethod<[_newCompany: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimApproved"
  ): TypedContractEvent<
    ClaimApprovedEvent.InputTuple,
    ClaimApprovedEvent.OutputTuple,
    ClaimApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimPaid"
  ): TypedContractEvent<
    ClaimPaidEvent.InputTuple,
    ClaimPaidEvent.OutputTuple,
    ClaimPaidEvent.OutputObject
  >;
  getEvent(
    key: "ClaimReviewed"
  ): TypedContractEvent<
    ClaimReviewedEvent.InputTuple,
    ClaimReviewedEvent.OutputTuple,
    ClaimReviewedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSubmitted"
  ): TypedContractEvent<
    ClaimSubmittedEvent.InputTuple,
    ClaimSubmittedEvent.OutputTuple,
    ClaimSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerAuthorized"
  ): TypedContractEvent<
    ReviewerAuthorizedEvent.InputTuple,
    ReviewerAuthorizedEvent.OutputTuple,
    ReviewerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerRevoked"
  ): TypedContractEvent<
    ReviewerRevokedEvent.InputTuple,
    ReviewerRevokedEvent.OutputTuple,
    ReviewerRevokedEvent.OutputObject
  >;

  filters: {
    "ClaimApproved(uint256,uint256)": TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;
    ClaimApproved: TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;

    "ClaimPaid(uint256,address)": TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;
    ClaimPaid: TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;

    "ClaimReviewed(uint256,address,uint8)": TypedContractEvent<
      ClaimReviewedEvent.InputTuple,
      ClaimReviewedEvent.OutputTuple,
      ClaimReviewedEvent.OutputObject
    >;
    ClaimReviewed: TypedContractEvent<
      ClaimReviewedEvent.InputTuple,
      ClaimReviewedEvent.OutputTuple,
      ClaimReviewedEvent.OutputObject
    >;

    "ClaimSubmitted(uint256,uint256,address)": TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
    ClaimSubmitted: TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;

    "ContractPaused(address)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "PolicyCreated(uint256,address)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;

    "ReviewerAuthorized(address)": TypedContractEvent<
      ReviewerAuthorizedEvent.InputTuple,
      ReviewerAuthorizedEvent.OutputTuple,
      ReviewerAuthorizedEvent.OutputObject
    >;
    ReviewerAuthorized: TypedContractEvent<
      ReviewerAuthorizedEvent.InputTuple,
      ReviewerAuthorizedEvent.OutputTuple,
      ReviewerAuthorizedEvent.OutputObject
    >;

    "ReviewerRevoked(address)": TypedContractEvent<
      ReviewerRevokedEvent.InputTuple,
      ReviewerRevokedEvent.OutputTuple,
      ReviewerRevokedEvent.OutputObject
    >;
    ReviewerRevoked: TypedContractEvent<
      ReviewerRevokedEvent.InputTuple,
      ReviewerRevokedEvent.OutputTuple,
      ReviewerRevokedEvent.OutputObject
    >;
  };
}
