/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPauserSet__factory } from "./IPauserSet__factory";
export { PrivateVehicleInsurance__factory } from "./PrivateVehicleInsurance__factory";
