/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPauserSet,
  IPauserSetInterface,
} from "../../../contracts/PrivateVehicleInsurance.sol/IPauserSet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "isAuthorizedPauser",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPauserSet__factory {
  static readonly abi = _abi;
  static createInterface(): IPauserSetInterface {
    return new Interface(_abi) as IPauserSetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPauserSet {
    return new Contract(address, _abi, runner) as unknown as IPauserSet;
  }
}
